#!/usr/bin/env python3
"""
gen_en_articles.py — Article database manager for aitoolbox.hk

Content is generated by Accio (Claude) via sessions_spawn — NOT by an external API.
This script handles: listing pending articles, writing completed content, status checks.

Usage:
  python scripts/gen_en_articles.py --list              # show pending articles
  python scripts/gen_en_articles.py --status            # show full status
  python scripts/gen_en_articles.py --write <slug>      # write content from stdin
  python scripts/gen_en_articles.py --reset <slug>      # mark article as pending again
"""

import json
import os
import sys
import re
import argparse
from datetime import date

# ─── Paths ────────────────────────────────────────────────────────────────────
BASE_DIR      = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ARTICLES_FILE = os.path.join(BASE_DIR, "data", "articles_en.json")
TOOLS_FILE    = os.path.join(BASE_DIR, "data", "tools_en.json")
DRAFTS_DIR    = os.path.join(BASE_DIR, "data", "_drafts_en")

os.makedirs(DRAFTS_DIR, exist_ok=True)

# ─── Article Topics ───────────────────────────────────────────────────────────
ARTICLE_TOPICS = [
    {
        "title": "Best AI Tools for Students: 20+ Tools You Actually Need in 2026",
        "slug": "best-ai-tools-for-students-2026",
        "category": "AI Tools",
        "keywords": "AI tools for students, best AI for students, student AI tools, AI for college",
        "target_word_count": 2000,
        "description": "Discover the best AI tools for students in 2026. From essay writing to math solving, we tested 20+ tools that actually help students save time and boost grades.",
    },
    {
        "title": "Free AI Image Generators With No Watermark (Tested & Ranked 2026)",
        "slug": "free-ai-image-generators-no-watermark",
        "category": "AI Image",
        "keywords": "free AI image generator no watermark, AI art generator free, best free AI art",
        "target_word_count": 1800,
        "description": "Tired of watermarked AI images? We tested 15+ free AI image generators and ranked the best ones with no watermark. See real examples and comparisons.",
    },
    {
        "title": "20 Best Free ChatGPT Alternatives in 2026 (No Credit Card)",
        "slug": "best-free-chatgpt-alternatives-2026",
        "category": "AI Chat",
        "keywords": "free ChatGPT alternatives, ChatGPT alternative free, AI chatbot free, best AI chat",
        "target_word_count": 2200,
        "description": "Looking for free ChatGPT alternatives? We compared 20 AI chatbots with free tiers — no credit card required. Find the best alternative for your needs.",
    },
    {
        "title": "AI Tools for Small Business: The Complete 2026 Guide",
        "slug": "ai-tools-for-small-business-2026",
        "category": "AI Tools",
        "keywords": "AI tools for small business, small business AI, AI for entrepreneurs, business AI tools",
        "target_word_count": 2000,
        "description": "The ultimate guide to AI tools for small business in 2026. Learn which tools save time, cut costs, and help you compete with bigger companies.",
    },
    {
        "title": "Best AI Tools for Beginners: Where to Start in 2026",
        "slug": "best-ai-tools-for-beginners-2026",
        "category": "AI Tools",
        "keywords": "AI tools for beginners, best AI for beginners, easy AI tools, start using AI",
        "target_word_count": 1800,
        "description": "New to AI? This beginner-friendly guide covers the easiest AI tools to start using today. No tech skills required — just practical tools that save time.",
    },
    {
        "title": "Free Midjourney Alternatives That Actually Work (2026)",
        "slug": "free-midjourney-alternatives-2026",
        "category": "AI Image",
        "keywords": "free Midjourney alternative, Midjourney free alternative, AI art tool free, image generator like Midjourney",
        "target_word_count": 1800,
        "description": "Can't afford Midjourney? These 10 free alternatives produce stunning AI art. We compared quality, speed, and features side by side with real examples.",
    },
    {
        "title": "AI Tools for Content Creators: Save 10+ Hours Per Week",
        "slug": "ai-tools-for-content-creators-2026",
        "category": "AI Tools",
        "keywords": "AI tools for content creators, content creator AI, AI for YouTubers, AI for creators",
        "target_word_count": 2000,
        "description": "Content creators are using AI to work smarter, not harder. Discover the AI tools that help YouTubers, bloggers, and social media creators save 10+ hours weekly.",
    },
    {
        "title": "Best AI Writing Tools Compared: Grammarly vs Jasper vs Writesonic (2026)",
        "slug": "ai-writing-tools-compared-2026",
        "category": "AI Writing",
        "keywords": "AI writing tools compared, Grammarly vs Jasper, best AI writing tool, AI writing assistant",
        "target_word_count": 2000,
        "description": "Grammarly vs Jasper vs Writesonic — which AI writing tool is best in 2026? We compared features, pricing, output quality, and real-world use cases.",
    },
    {
        "title": "AI Productivity Tools: Build Your Ultimate 2026 Workflow",
        "slug": "ai-productivity-tools-2026-workflow",
        "category": "AI Productivity",
        "keywords": "AI productivity tools, AI workflow, productivity AI, best AI for productivity",
        "target_word_count": 2000,
        "description": "Build a complete AI-powered productivity workflow in 2026. We show you which tools to combine for maximum efficiency at work and in daily life.",
    },
    {
        "title": "Best Free AI Video Generators in 2026 (Ranked & Tested)",
        "slug": "best-free-ai-video-generators-2026",
        "category": "AI Video",
        "keywords": "free AI video generator, AI video maker free, best AI video tool, text to video AI free",
        "target_word_count": 1800,
        "description": "Want to create videos with AI for free? We tested 12+ AI video generators and ranked the best ones. See real output examples and compare features.",
    },
    {
        "title": "AI Tools for Teachers: Automate Grading, Lesson Plans & More",
        "slug": "ai-tools-for-teachers-2026",
        "category": "AI Tools",
        "keywords": "AI tools for teachers, AI for education, teacher AI tools, AI grading tools",
        "target_word_count": 1800,
        "description": "Teachers are using AI to save hours on grading, lesson planning, and admin work. Discover the best AI tools for educators in 2026.",
    },
    {
        "title": "Best AI Coding Assistants Compared (2026): Cursor vs Copilot vs Claude Code",
        "slug": "best-ai-coding-assistants-2026",
        "category": "AI Coding",
        "keywords": "AI coding assistant, best AI for coding, Cursor vs Copilot, AI code generator",
        "target_word_count": 2200,
        "description": "Which AI coding assistant is best in 2026? We compared Cursor, GitHub Copilot, Claude Code, and more on speed, accuracy, and real coding tasks.",
    },
    {
        "title": "Free AI Tools No Sign Up Required (Instant Access 2026)",
        "slug": "free-ai-tools-no-sign-up-2026",
        "category": "AI Tools",
        "keywords": "free AI tools no sign up, AI tools no registration, instant AI tools, use AI without account",
        "target_word_count": 1800,
        "description": "No time to create accounts? These 15+ AI tools work instantly with no sign up required. Just open and start using them right away.",
    },
    {
        "title": "AI Tools for Marketers: The Complete 2026 Toolkit",
        "slug": "ai-tools-for-marketers-2026",
        "category": "AI Tools",
        "keywords": "AI tools for marketers, marketing AI tools, AI for marketing, digital marketing AI",
        "target_word_count": 2000,
        "description": "The complete AI toolkit for marketers in 2026. From copywriting to SEO to ad optimization — discover which tools give you the biggest competitive edge.",
    },
    {
        "title": "ChatGPT vs Gemini vs Claude: Which AI Chatbot Is Best in 2026?",
        "slug": "chatgpt-vs-gemini-vs-claude-2026",
        "category": "AI Chat",
        "keywords": "ChatGPT vs Gemini vs Claude, best AI chatbot 2026, AI chatbot comparison, which AI is best",
        "target_word_count": 2200,
        "description": "ChatGPT, Gemini, or Claude? We put the three biggest AI chatbots head to head in writing, coding, research, and reasoning. See which one wins.",
    },
    {
        "title": "Best AI Presentation Tools for 2026: Create Slides in Minutes",
        "slug": "best-ai-presentation-tools-2026",
        "category": "AI Office",
        "keywords": "AI presentation tool, AI slide maker, AI PowerPoint, create slides with AI",
        "target_word_count": 1600,
        "description": "Create professional presentations in minutes with AI. We compared the best AI slide makers — from Gamma to Beautiful.ai to Canva AI.",
    },
    {
        "title": "AI Resume Builders: Create a Professional Resume in Minutes",
        "slug": "ai-resume-builders-2026",
        "category": "AI Tools",
        "keywords": "AI resume builder, resume AI tool, AI resume maker, create resume with AI",
        "target_word_count": 1500,
        "description": "Need a resume fast? These AI resume builders create professional, ATS-friendly resumes in minutes. We tested the best ones for 2026.",
    },
    {
        "title": "Best AI Voice Generators & Text to Speech Tools (2026)",
        "slug": "best-ai-voice-generators-tts-2026",
        "category": "AI Audio",
        "keywords": "AI voice generator, text to speech AI, best TTS, AI voice maker, realistic AI voice",
        "target_word_count": 1800,
        "description": "From ElevenLabs to Speechify, we compared the best AI voice generators and text to speech tools. Hear real samples and find the best one for your needs.",
    },
    {
        "title": "AI Tools for Real Estate Agents: Close More Deals in 2026",
        "slug": "ai-tools-for-real-estate-agents-2026",
        "category": "AI Tools",
        "keywords": "AI tools for real estate, real estate AI, AI for realtors, property AI tools",
        "target_word_count": 1600,
        "description": "Real estate agents using AI close more deals. Discover the AI tools that help with listing descriptions, virtual staging, lead generation, and client communication.",
    },
    {
        "title": "Best AI Translation Tools Compared (2026): DeepL vs Google vs More",
        "slug": "best-ai-translation-tools-2026",
        "category": "AI Translation",
        "keywords": "AI translation tool, best AI translator, DeepL vs Google Translate, AI translation compared",
        "target_word_count": 1800,
        "description": "Which AI translation tool is most accurate? We tested DeepL, Google Translate, and other AI translators with real texts in 10+ languages.",
    },
]


# ─── Helpers ──────────────────────────────────────────────────────────────────

def load_articles():
    if os.path.exists(ARTICLES_FILE):
        with open(ARTICLES_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return []


def save_articles(articles):
    with open(ARTICLES_FILE, "w", encoding="utf-8") as f:
        json.dump(articles, f, ensure_ascii=False, indent=2)


def load_tools():
    if os.path.exists(TOOLS_FILE):
        with open(TOOLS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return []


def get_existing_slugs(articles):
    return {a["slug"] for a in articles}


def get_pending(articles):
    existing = get_existing_slugs(articles)
    return [t for t in ARTICLE_TOPICS if t["slug"] not in existing]


# ─── Writing Prompt (for Accio to use when generating) ────────────────────────

def build_prompt(topic, tools):
    """
    Returns the full prompt Accio should use to generate this article.
    Call this from the main agent to get the prompt, then generate and --write back.
    """
    relevant = []
    kws = topic["keywords"].lower().split(",")
    for t in tools:
        name = t.get("name", "")
        cat  = t.get("category", "")
        desc = t.get("description", "")
        slug = t.get("slug", "")
        if any(k.strip() in (name + cat + desc).lower() for k in kws):
            relevant.append(f"- {name} (/{slug}/): {desc[:100]}")

    tool_block = ""
    if relevant:
        tool_block = "\n\nTools on aitoolbox.hk you can naturally reference (use slug as link path):\n" + "\n".join(relevant[:12])

    system = """You are a senior tech journalist who has covered AI tools for 6 years. You write for a savvy, skeptical audience — people who have been burned by AI hype before and only want honest, specific, useful information.

VOICE RULES (non-negotiable):
- Write like a human who has actually used these tools, not like a product description
- Use short sentences. Mix them with longer ones for rhythm.
- Opinions are welcome: "X is genuinely impressive", "Y is overhyped", "Z works surprisingly well"
- Specific beats general: "$20/month" beats "affordable", "generates in 4 seconds" beats "fast"
- Imperfections are credible: mention real limitations, not just praise
- Use contractions naturally: "it's", "you'll", "don't", "can't"
- No corporate buzzwords: avoid "leverage", "utilize", "seamlessly", "robust", "cutting-edge", "revolutionary", "game-changing", "empower", "streamline"
- No AI-smell phrases: avoid "In today's fast-paced world", "In conclusion", "It's worth noting that", "Delve into", "Comprehensive", "Dive in", "Let's explore", "As an AI", "I hope this helps"
- First paragraph: drop the reader into a real situation — no thesis statements
- Headers should be informative, not clickbait: "Notion AI: Good for drafts, bad for research" beats "The Best Tool for Your Needs"

STRUCTURE:
- 2000+ words (strict minimum)
- Intro: 1 short punchy paragraph, no summary of what you'll cover
- Body: 5–8 H2 sections with specific tool names, real prices, actual limitations
- 1 comparison table (markdown)
- 3–5 FAQ at end (question as H3, answer 40–70 words)
- No "Conclusion" header — end with a direct recommendation paragraph

SEO KEYWORD RULES (Google ranking depends on this):
- The PRIMARY keyword (first keyword listed) must appear naturally 3–5 times in the article body. Do not stuff it — weave it into sentences where it fits. Example: if primary keyword is "AI tools for teachers", use it in natural sentences like "The best AI tools for teachers I've found are..." or "Most AI tools for teachers fall into two camps..."
- LONG-TAIL keywords (remaining keywords listed) must each appear at least 1–2 times, woven naturally into relevant sections
- The primary keyword MUST appear in: (1) the first 100 words of the article, (2) at least one H2 header, (3) the final recommendation paragraph
- Do NOT keyword-stuff: if a sentence sounds unnatural with the keyword, rephrase it so the keyword fits naturally
- Headers can paraphrase the keyword rather than use it verbatim — that's fine

INTERNAL LINK FORMAT (critical — wrong format breaks the site):
- Link to tools on aitoolbox.hk using EXACT markdown: [Tool Name](/tool-slug/)
- Example: [ChatGPT](/chatgpt/) or [Grammarly](/grammarly-ai/)
- Never use bare slugs like (/chatgpt/) without the link text
- Never use full URLs like https://aitoolbox.hk/chatgpt/
- Only link to tools provided in the "Tools to reference" list below"""

    user = f"""Write the full article. Topic metadata:

Title: {topic['title']}
Keywords: {topic['keywords']}
Meta description: {topic['description']}
{tool_block}

Output: raw Markdown only. No frontmatter, no JSON, no explanation. Start directly with the first paragraph (no H1 title — the site renders the title separately).

KEYWORD CHECKLIST before finishing — verify these are met:
1. Primary keyword appears 3–5 times in body text
2. Each long-tail keyword appears at least once
3. Primary keyword is in the first 100 words
4. Primary keyword appears in at least one H2
5. Internal links use correct format [Name](/slug/)"""

    return system, user


# ─── CLI ──────────────────────────────────────────────────────────────────────

def cmd_list(args):
    articles = load_articles()
    pending  = get_pending(articles)
    if not pending:
        print("All 20 articles already generated.")
        return
    print(f"Pending ({len(pending)}/{len(ARTICLE_TOPICS)}):")
    for i, t in enumerate(pending, 1):
        print(f"  {i:2d}. {t['slug']}")
        print(f"       {t['title']}")


def cmd_status(args):
    articles = load_articles()
    existing = get_existing_slugs(articles)
    print(f"{'SLUG':<45} {'STATUS':<10} {'WORDS'}")
    print("-" * 70)
    for t in ARTICLE_TOPICS:
        slug = t["slug"]
        if slug in existing:
            a  = next(x for x in articles if x["slug"] == slug)
            wc = len(a.get("content", "").split())
            print(f"  {slug:<43} {'done':<10} {wc}")
        else:
            print(f"  {slug:<43} {'pending':<10} —")


def cmd_prompt(args):
    """Print the prompt for a given slug (for Accio to use)."""
    slug = args.slug
    topic = next((t for t in ARTICLE_TOPICS if t["slug"] == slug), None)
    if not topic:
        print(f"Unknown slug: {slug}", file=sys.stderr)
        sys.exit(1)
    tools   = load_tools()
    system, user = build_prompt(topic, tools)
    print("=== SYSTEM PROMPT ===")
    print(system)
    print("\n=== USER PROMPT ===")
    print(user)


def cmd_write(args):
    """Write a generated article (content from a draft file or stdin) into articles_en.json."""
    slug  = args.slug
    topic = next((t for t in ARTICLE_TOPICS if t["slug"] == slug), None)
    if not topic:
        print(f"Unknown slug: {slug}", file=sys.stderr)
        sys.exit(1)

    # Read content from draft file if exists, else stdin
    draft_file = os.path.join(DRAFTS_DIR, f"{slug}.md")
    if os.path.exists(draft_file):
        with open(draft_file, "r", encoding="utf-8") as f:
            content = f.read().strip()
        print(f"Reading from draft: {draft_file}")
    else:
        print(f"Reading content from stdin (paste markdown, then Ctrl+Z on Windows):")
        content = sys.stdin.read().strip()

    if len(content.split()) < 500:
        print(f"Content too short ({len(content.split())} words). Aborting.", file=sys.stderr)
        sys.exit(1)

    articles = load_articles()
    existing = get_existing_slugs(articles)

    today = date.today()
    article = {
        "title":       topic["title"],
        "slug":        slug,
        "date":        today.strftime("%Y-%m-%d"),
        "dateFull":    today.strftime("%B %d, %Y"),
        "category":    topic["category"],
        "description": topic["description"],
        "keywords":    topic["keywords"],
        "lang":        "en",
        "type":        "E",
        "content":     content,
    }

    if slug in existing:
        # Update existing
        articles = [a if a["slug"] != slug else article for a in articles]
        print(f"Updated: {slug} ({len(content.split())} words)")
    else:
        articles.append(article)
        print(f"Added: {slug} ({len(content.split())} words)")

    save_articles(articles)

    # Remove draft file after writing
    if os.path.exists(draft_file):
        os.remove(draft_file)
        print(f"Removed draft: {draft_file}")


def cmd_reset(args):
    slug     = args.slug
    articles = load_articles()
    before   = len(articles)
    articles = [a for a in articles if a["slug"] != slug]
    if len(articles) < before:
        save_articles(articles)
        print(f"Reset: {slug} removed from articles_en.json (now pending)")
    else:
        print(f"Not found: {slug}")


def cmd_draft(args):
    """Show the draft file path for a slug."""
    slug       = args.slug
    draft_file = os.path.join(DRAFTS_DIR, f"{slug}.md")
    print(draft_file)


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Article manager for aitoolbox.hk")
    sub    = parser.add_subparsers(dest="cmd")

    sub.add_parser("list",   help="List pending articles")
    sub.add_parser("status", help="Show full status table")

    p_prompt = sub.add_parser("prompt", help="Print generation prompt for a slug")
    p_prompt.add_argument("slug")

    p_write = sub.add_parser("write", help="Write article content into articles_en.json")
    p_write.add_argument("slug")

    p_reset = sub.add_parser("reset", help="Remove an article (mark as pending)")
    p_reset.add_argument("slug")

    p_draft = sub.add_parser("draft", help="Show draft file path for a slug")
    p_draft.add_argument("slug")

    args = parser.parse_args()

    if args.cmd == "list":
        cmd_list(args)
    elif args.cmd == "status":
        cmd_status(args)
    elif args.cmd == "prompt":
        cmd_prompt(args)
    elif args.cmd == "write":
        cmd_write(args)
    elif args.cmd == "reset":
        cmd_reset(args)
    elif args.cmd == "draft":
        cmd_draft(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
